Repository reorganisation + injecting ConfigFactory to Image class
sk-rp-ta/img-in pull request #2
Opened 2023-08-19 16:23 UTC by sk-rp-ta

2023-08-20 18:12 UTC, whiskeyo requested changes

2023-08-20 18:12 UTC, whiskeyo commented on img-in/Image.cpp
> +void Image::load(const std::filesystem::path image, Config factory = std::make_unique<detail::ConfigFactory>())
I checked the size of `std::filesystem::path` using this code:

```cpp
std::cout << sizeof(std::filesystem::path) << std::endl;
std::cout << sizeof(uint64_t) << std::endl;
```

and `std::filesystem::path` is 40, while `uint64_t` is 8. I guess that means that it'd be more efficient to pass it by reference.

2023-08-20 18:12 UTC, whiskeyo commented on img-in/Image.cpp
> +void Image::load(const std::filesystem::path image, Config factory = std::make_unique<detail::ConfigFactory>())
Maybe `imagePath`?

2023-08-20 18:12 UTC, whiskeyo commented on img-in/Image.cpp
> +        throw std::runtime_error("File does not exist");
Change it to "File <filename> does not exist"

2023-08-20 18:12 UTC, whiskeyo commented on img-in/Image.cpp
> +void Image::load(const std::filesystem::path image, Config factory = std::make_unique<detail::ConfigFactory>())
I'm wondering whether having default arguments is a good practice :(

2023-08-20 18:12 UTC, whiskeyo commented on img-in/Image.hpp
> +    using Config = std::unique_ptr<interface::IConfigFactory>;
I'd change it to be more descriptive, you do not have `Config`, but `ConfigFactory` here.

2023-08-20 18:12 UTC, whiskeyo commented on img-in/detail/inc/ConfigFactory.hpp
> +#include "../if/IConfigFactory.hpp"
You might think of changing `CMakeLists.txt` to avoid having to use `"../something"`, but `<something>` instead.

2023-08-20 18:12 UTC, whiskeyo commented on img-in/detail/inc/FilesystemWrapper.hpp
> +    bool exists(const std::filesystem::path path);
Also const ref here

2023-08-20 18:12 UTC, whiskeyo commented on tests/CMakeLists.txt
> -include_directories(${PROJECT_SOURCE_DIR}/src)
You might keep `include_directories(${PROJECT_SOURCE_DIR}/img-in/src)` or sth like that, so it is easier to include things in UTs

2023-08-20 18:12 UTC, whiskeyo commented on tests/TestImage.cpp
> +using namespace testing;
I'd avoid using namespaces like this, even if it is .cpp file with tests. It's easier to read the code with namespaces, especially when they are not nested.

2023-08-20 18:12 UTC, whiskeyo commented on tests/TestImage.cpp
> +    StrictFilesystemMock* filesystemMockPtr = filesystemMock.get();
If these are fields in the class, shouldn't you initialize them with `{}` instead of `=`?

2023-08-20 18:12 UTC, whiskeyo commented on tests/TestImage.cpp
> +    EXPECT_CALL(*filesystemMockPtr, exists(_)).WillOnce(Return(false));
You might match it with `path`

2023-08-20 18:12 UTC, whiskeyo commented on tests/mocks/ConfigFactoryMock.hpp
> +    MOCK_METHOD0(createFilesystem, std::unique_ptr<imgin::interface::IFilesystem>());
Which gtest are you using? You should keep `MOCK_METHOD` without the number of arguments, this is already deprecated.

2023-08-20 18:23 UTC, whiskeyo commented on img-in/Image.cpp
> +        throw std::runtime_error("File does not exist");
`"File \"filename\" does not exist"`, sorry :)

2023-08-22 18:20 UTC, sk-rp-ta commented on img-in/Image.cpp
> +void Image::load(const std::filesystem::path image, Config factory = std::make_unique<detail::ConfigFactory>())
Coudn't find a better idea to introduce dependency injection

2023-08-22 18:21 UTC, sk-rp-ta commented on img-in/Image.hpp
> +    using Config = std::unique_ptr<interface::IConfigFactory>;
TBH I wanted to hide it a bit from user POV. It should not be used by casual user anyway

2023-08-22 18:23 UTC, sk-rp-ta commented on tests/TestImage.cpp
> +    StrictFilesystemMock* filesystemMockPtr = filesystemMock.get();
Should be the same, but I can change it

2023-08-22 18:24 UTC, sk-rp-ta commented on tests/TestImage.cpp
> +    EXPECT_CALL(*filesystemMockPtr, exists(_)).WillOnce(Return(false));
I am always wondering which approach is better: to point that ANY argument should return false, or to check if it is called with the given one. Ill guess Ill go for the second as you pointed

2023-08-22 18:30 UTC, sk-rp-ta commented on tests/TestImage.cpp
> +using namespace testing;
Sorry but WillOnce(testing::Return(x)) looks disgusting to me :(

2023-08-26 20:49 UTC, whiskeyo commented on img-in/Image.hpp
> +    using Config = std::unique_ptr<interface::IConfigFactory>;
If it's in hpp, it will be visible by the user, especially when it is in public part.

2023-08-27 14:31 UTC, sk-rp-ta commented on img-in/Image.hpp
> +    using Config = std::unique_ptr<interface::IConfigFactory>;
Yeah, point was to hide the fact that this is ConfigFactory and leave it like Config

2023-09-14 22:13 UTC, whiskeyo approved these changes

2023-09-16 11:16 UTC, merged